version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - '80:80'
      #- '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- ./build/certs:/etc/nginx/certs
      #- ./build/htpasswd:/etc/nginx/htpasswd

  db:
    image: percona
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - ./build/env

  mage:
    build:
      context: ./build
      dockerfile: apache
    restart: always
    hostname: mage
    volumes:
      - ./data/www/mage:/var/www/html
      - ./build/authorized_keys:/root/.ssh/authorized_keys
    environment:
      - VIRTUAL_HOST=http://127.0.0.1
    env_file:
      - ./build/env
    #ports: '2222:22'
